name: 'build-test'
on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-test
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - uses: ./

      - run: bundletool help

      - run: bundletool version